title: Zeal
url: "https://zeal.is"
baseurl:
google_analytics_key: UA-103610351-1
google_maps_javascript_api_key: AIzaSyB7WL14WhMO4s3APFaIB5vnJlUxCmO864k
disqus_shortname: zeal-2

# Default description in social shares for the jekyll-seo-tag gem
description: "Community for sustainability entrepreneurs and product leaders."

# Author details for the jekyll-seo-tag gem
author:
  name: Andrew Skotzko
  email: info@zeal.is
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name:
  links:

collections:
  staff_members:
    output: false
  clients:
    output: false

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"
  - "jemoji"
  - "jekyll-redirect-from"
  - "jekyll-sitemap"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - AngelList
  # - Pinterest
  # - Tumblr
  # - Twitter
  # - YouTube
  # - RSS

sumo_me_site_id: 8535dc73db7e897ed13211076b6f65023ceea1492d91364bd3d75f3f80f27fbd